version: "3"

services:
  wordpress:
    build: services/wordpress
    ports:
      - "8000:80"
  db:
    image: mariadb:10.6
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      TZ: Asia/Tokyo
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
